pull_request_rules:
- actions:
    review:
      type: APPROVE
  conditions:
  - base=20231205180758/test_review_normal/main
  - '#approved-reviews-by=0'
  - '#review-requested=0'
  name: approve
- actions:
    review:
      message: WTF?
      type: REQUEST_CHANGES
  conditions:
  - base=20231205180758/test_review_normal/main
  - '#approved-reviews-by>=1'
  - '#requested-reviews=0'
  name: requested
