pull_request_rules:
- actions:
    review:
      type: APPROVE
  conditions:
  - base=20231211172907/test_request_reviews_already_max/main
  - '#requested-reviews=0'
  name: approve
- actions:
    request_reviews:
      users:
      - mergify-test1
      - mergify-test4
  conditions:
  - base=20231211172907/test_request_reviews_already_max/main
  name: request_reviews
