pull_request_rules:
- actions:
    queue:
      method: merge
      name: default
      update_method: rebase
  conditions:
  - base=20230509130222/test_strict_status_check_with_rebase_update_method_and_no_bot_account/main
  - label=queue
  name: Queue on label
queue_rules:
- conditions: []
  name: default
