pull_request_rules:
- actions:
    review:
      message: Thank you {{hello}}
      type: REQUEST_CHANGES
  conditions:
  - base=20221024152324/test_review_template_attribute_error/main
  name: review
